spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session

  redis:
    host: localhost
    port: 6379

  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true

    generate-ddl: true

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5433/resource
    username: postgres
    password: nhjkmuhjv
    platform: postgresql

  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api
  port: 9001


ui.host: http://localhost:9528/

#logging:
#  level:
#    root: DEBUG
